/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 lamp2.gltf --transform 
Files: lamp2.gltf [1.11MB] > lamp2-transformed.glb [127.23KB] (89%)
*/
'use client';

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LampSecond(props) {
  const { nodes, materials } = useGLTF('/models/lamp2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Torus.geometry} material={materials.lamp_upper} position={[0, 1.36, 0]} scale={[1.72, 3.6, 1.72]} />
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[0, 0.533, 0]} scale={[1.2, 1, 1.2]}  />
    </group>
  )
}

useGLTF.preload('/models/lamp2-transformed.glb')
