/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 vase2.gltf --transform 
Files: vase2.gltf [744.32KB] > vase2-transformed.glb [46.68KB] (94%)
*/
'use client';

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function VaseSecond(props) {
  const { nodes, materials } = useGLTF('/models/vase2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials.vase1} position={[0, 0.837, 0]} scale={[0.577, 0.945, 0.577]} />
    </group>
  )
}

useGLTF.preload('/models/vase2-transformed.glb')
