/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 vase3.gltf --transform 
Files: vase3.gltf [781.2KB] > vase3-transformed.glb [47.31KB] (94%)
*/
'use client';

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function VaseThird(props) {
  const { nodes, materials } = useGLTF('/models/vase3-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials.vase1} position={[0, 0.837, 0]} rotation={[0, 0.337, 0]} scale={[0.577, 0.945, 0.577]} />
    </group>
  )
}

useGLTF.preload('/models/vase3-transformed.glb')
