/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 vase1.gltf --transform 
Files: vase1.gltf [536.6KB] > vase1-transformed.glb [43.98KB] (92%)
*/
'use client';

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function VaseFirst(props) {
  const { nodes, materials } = useGLTF('/models/vase1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials.vase1} position={[0, 0.837, 0]} scale={[0.577, 0.945, 0.577]} />
    </group>
  )
}

useGLTF.preload('/models/vase1-transformed.glb')
